@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2ODk2ODU3NjZ9.xi3J8Qis-FAub2ROB1YzCqrH7ltb37p8MkOMqfwThlo

### Budgets Index
GET http://localhost:3000/budgets.json
Authorization: Bearer {{jwt}}

### Budgets Show
GET http://localhost:3000/budgets/2.json
Authorization: Bearer {{jwt}}

### Budgets Create
POST http://localhost:3000/budgets.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "category_id":"10",
  "amount":1000
}

### Budgets Update
PATCH http://localhost:3000/budgets/3.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
"amount":1600
}

### Delete Budget
DELETE http://localhost:3000/budgets/1.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

### Transactions Index
GET http://localhost:3000/transactions.json
Authorization: Bearer {{jwt}}

### Transactions Show
GET http://localhost:3000/transactions/4.json
Authorization: Bearer {{jwt}}

### Transactions Create
POST http://localhost:3000/transactions.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "date":20230716,
  "description":"test",
  "category_id":18,
  "amount":22,
  "income":false,
  "expense":true
}

### Transactions Update
PATCH http://localhost:3000/transactions/4.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
"amount":25
}

### Delete Transaction
DELETE http://localhost:3000/transactions/4.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

### User Sign-Up
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "email":"zachary@test.com",
  "password":"password",
  "password_confirmation":"password"
}

### User Login
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "zachary@test.com",
  "password":"password"
}




