@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2ODk1OTczMDd9.ri0ljcVtDH8z05WoJTibBr_XVvcoBsVDsdNo6ssOg4E

### Budgets Index
GET http://localhost:3000/budgets.json

### Budgets Show
GET http://localhost:3000/budgets/2.json

### Budgets Create
POST http://localhost:3000/budgets.json
Content-Type: application/json

{
  "category_id":"1",
  "amount":50,
  "user_id":2
}

### Budgets Update
PATCH http://localhost:3000/budgets/3.json
Content-Type: application/json

{
"amount":1600
}

### Delete Budget
DELETE http://localhost:3000/budgets/1.json
Content-Type: application/json

### Transactions Index
GET http://localhost:3000/transactions.json

### Transactions Show
GET http://localhost:3000/transactions/1.json

### Transactions Create
POST http://localhost:3000/transactions.json
Content-Type: application/json

{
  "date":20230710,
  "description":"coffee date",
  "category_id":13,
  "amount":10.01,
  "income":false,
  "expense":true,
  "user_id":3
}

### Transactions Update
PATCH http://localhost:3000/transactions/1.json
Content-Type: application/json

{
"amount":223
}

### Delete Transaction
DELETE http://localhost:3000/transactions/1.json
Content-Type: application/json

### User Sign-Up
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "email":"zachary@test.com",
  "password":"password",
  "password_confirmation":"password"
}

### User Login
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "zachary@test.com",
  "password":"password"
}




