# Users
User.create(email: "kathleen@test.com", password: "password")
User.create(email: "bristol@test.com", password: "password")
User.create(email: "atlas@test.com", password: "password")
# Categories
Category.create(name: "Auto and Transport")
Category.create(name: "Bills and Utilities")
Category.create(name: "Business Services")
Category.create(name: "Education")
Category.create(name: "Entertainment")
Category.create(name: "Fees and Charges")
Category.create(name: "Financial")
Category.create(name: "Food and Dining")
Category.create(name: "Gifts and Donations")
Category.create(name: "Health and Fitness")
Category.create(name: "Home")
Category.create(name: "Income")
Category.create(name: "Investments")
Category.create(name: "Kids")
Category.create(name: "Loans")
Category.create(name: "Misc Expenses")
Category.create(name: "Personal Care")
Category.create(name: "Pets")
Category.create(name: "Shopping")
Category.create(name: "Taxes")
Category.create(name: "Transfer")
Category.create(name: "Travel")
# Budgets
Budget.create(amount: 200, category_id: 8, user_id: 1)
Budget.create(amount: 1000, category_id: 5, user_id: 2)
Budget.create(amount: 1500, category_id: 9, user_id: 2)
# Transactions
Transaction.create(date: 20230713, description: "picked up groceries", category_id: 8, amount: 123, income: false, expense: true, user_id: 1)
Transaction.create(date: 20230713, description: "new tires", category_id: 1, amount: 500, income: false, expense: true, user_id: 2)
Transaction.create(date: 20230713, description: "dog food", category_id: 18, amount: 80, income: false, expense: true, user_id: 3)
Transaction.create(date: 20230722, description: "electric", category_id: 2, amount: 123, income: false, expense: true, user_id: 2)
# 888888
Transaction.create(date: 20230701, description: "taxes", category_id: 7, amount: 220, income: false, expense: true, user_id: 2)
Transaction.create(date: 20230722, description: "Alaska Cruise 2023", category_id: 22, amount: "4000", income: false, expense: true, user_id: 2)
Transaction.create(date: 20230722, description: "Ulta - Moisturizer", category_id: 19, amount: 50, income: false, expense: true, user_id: 2)
Transaction.create(date: 20230722, description: "Target-  Fall Decor", category_id: 19, amount: "515", income: false, expense: true, user_id: 2)
Transaction.create(date: 20230722, description: "LuluLemon - leggings", category_id: 19, amount: "110", income: false, expense: true, user_id: 2)
Transaction.create(date: 20230722, description: "Pay", category_id: 12, amount: 3054, income: true, expense: false, user_id: 2)
